version: 0.0
os: linux

files:
  - source: /
    destination: /var/www/html

permissions:
  - object: /var/www/html
    pattern: "**"
    owner: ubuntu
    group: ubuntu

hooks:
  BeforeInstall:
    - location: scripts/install_dependencies.sh
      timeout: 300
      runas: ubuntu

  AfterInstall:
    - location: scripts/build_angular.sh
      timeout: 300
      runas: ubuntu

  ApplicationStart:
    - location: scripts/start_angular.sh
      timeout: 300
      runas: ubuntu
