version: 0.2
env:
  variables:
    S3_BUCKET: "angular-site-first-12"
phases:
  install:
    runtime-versions:
      nodejs: 18
  pre_build:
    commands:
      - echo Installing source NPM dependencies...
      - npm install --legacy-peer-deps
      - npm install -g @angular/cli
  build:
    commands:
      - echo Build started on `date`
      - ng build --configuration production --aot
  post_build:
     commands:
      
      - echo Build completed on `date`
      - aws cloudfront create-invalidation --distribution-id E1HTVES7IBA1GD --paths /index.html
      
artifacts:
  files:
      - '**/*'
  base-directory: 'dist*'
  discard-paths: yes
